filtered:
    fuck
    shit
    pussy
    anal
    asshole
    ass
    asswipe
    motherfucker
    goddamn
    vagina
    penis
    dick
    vag
    anus
    bitch
    cunt
    porn
    lesbian
    gay
    bloodyhell
    hellhole
    bitchass
    fucker
    faggot
    whore
    hoe
    ho
    slut
    skank
    